DROP TABLE node_neigh;
CREATE TABLE node_neigh
(
  node_id bigint NOT NULL,
  neigh_id bigint NOT NULL,
  way_id bigint,
  CONSTRAINT pk_neigh_nodes PRIMARY KEY (node_id, neigh_id, way_id)
);

DROP TABLE ref_nodes;
CREATE TABLE ref_nodes
(
  id SERIAL PRIMARY KEY,
  module TEXT NOT NULL,
  access text,
  "addr:housename" text,
  "addr:housenumber" text,
  "addr:interpolation" text,
  admin_level text,
  aerialway text,
  aeroway text,
  amenity text,
  area text,
  barrier text,
  bicycle text,
  brand text,
  bridge text,
  boundary text,
  building text,
  construction text,
  covered text,
  culvert text,
  cutting text,
  denomination text,
  disused text,
  embankment text,
  foot text,
  "generator:source" text,
  harbour text,
  highway text,
  historic text,
  horse text,
  intermittent text,
  junction text,
  landuse text,
  layer text,
  leisure text,
  lock text,
  man_made text,
  military text,
  motorcar text,
  name text,
  "natural" text,
  oneway text,
  operator text,
  population text,
  power text,
  power_source text,
  place text,
  railway text,
  ref text,
  religion text,
  route text,
  service text,
  shop text,
  sport text,
  surface text,
  toll text,
  tourism text,
  "tower:type" text,
  tracktype text,
  tunnel text,
  type text,
  water text,
  waterway text,
  wetland text,
  width text,
  wood text,
  z_order integer,
  tags hstore
);

DROP TABLE ref_relations;
CREATE TABLE ref_relations
(
  id SERIAL PRIMARY KEY,
  module TEXT NOT NULL,
  parent_relation INT,
  access text,
  "addr:housename" text,
  "addr:housenumber" text,
  "addr:interpolation" text,
  admin_level text,
  aerialway text,
  aeroway text,
  amenity text,
  area text,
  barrier text,
  bicycle text,
  brand text,
  bridge text,
  boundary text,
  building text,
  construction text,
  covered text,
  culvert text,
  cutting text,
  denomination text,
  disused text,
  embankment text,
  foot text,
  "generator:source" text,
  harbour text,
  highway text,
  historic text,
  horse text,
  intermittent text,
  junction text,
  landuse text,
  layer text,
  leisure text,
  lock text,
  man_made text,
  military text,
  motorcar text,
  name text,
  "natural" text,
  network text,
  oneway text,
  operator text,
  population text,
  power text,
  power_source text,
  place text,
  railway text,
  ref text,
  religion text,
  route text,
  service text,
  shop text,
  sport text,
  surface text,
  toll text,
  tourism text,
  "tower:type" text,
  tracktype text,
  tunnel text,
  type text,
  water text,
  waterway text,
  wetland text,
  width text,
  wood text,
  z_order integer,
  tags hstore,
  CONSTRAINT fk_ref_relations_parent FOREIGN KEY (parent_relation) REFERENCES ref_relations (id)
);
